from typing import List
from fastapi import APIRouter
from app.features.ai_insights.schemas import AIInsightDTO, AISummaryDTO

router = APIRouter(prefix="/v1/ai-insights", tags=["6. AI Executive Insights"])

@router.get("/summary", response_model=AISummaryDTO, summary="Get LLM Executive Digest Summary")
async def get_summary() -> AISummaryDTO:
    """Retrieve natural language executive summary digest generated by AI."""
    return AISummaryDTO(
        headline="Strong positive overall sentiment (+0.68 Index)",
        summary="Overall feedback sentiment remains strong at +0.68 Index (78% Positive), driven by praise for UI speed and SDK documentation.",
        keyOpportunities=["Promote GraphQL SDK tutorial", "Expand developer portal guides"],
        riskCount=1,
    )

@router.get("/recommendations", response_model=List[AIInsightDTO], summary="Get Prioritized AI Risk & Action Items")
async def get_recommendations() -> List[AIInsightDTO]:
    """Retrieve AI-driven root cause diagnostics, risk alerts, and action items."""
    return [
        AIInsightDTO(
            id="ai-1",
            title="Payment Checkout Friction Identified",
            category="root_cause",
            severity="warning",
            description="AI NLP cluster identified a 14% drop in billing sentiment due to 3D Secure WebKit mobile timeout.",
            impactScore=89,
            suggestedAction="Deploy hotfix for WebKit iframe postMessage event listener in Checkout v2.",
            affectedUsersCount=1420,
            timestamp="10 mins ago",
        ),
        AIInsightDTO(
            id="ai-2",
            title="Surge in Developer API Satisfaction",
            category="opportunity",
            severity="success",
            description="SDK 4.0 launch generated 88% positive sentiment among developer persona accounts.",
            impactScore=94,
            suggestedAction="Promote GraphQL SDK tutorial on developer portal homepage.",
            affectedUsersCount=3800,
            timestamp="1 hour ago",
        ),
    ]
